version: '3.8'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    restart: always  
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=localhost
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: host.docker.internal

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - app-network

  mysql:
    image: mysql:8
    platform: linux/x86_64
    container_name: mysql
    restart: always
    ports:
      - "6666:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 500M
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "9090:80"
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 1024M
    volumes: 
      - ./docker/phpmyadmin/upload.ini:/usr/local/etc/php/conf.d/upload.ini
    networks:
      - app-network   

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge 
    
volumes:
  mysql_data:
    
